server:
  port: 8861

spring:
  application:
    name: xc-zookeeper-client

  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
    discovery:
      enabled: true # 只开启服务发现
    loadbalancer:
      ribbon:
        enabled: true # 默认是true ,默认线性访问,如果打开,同时启动两个服务的时候,curl去访问,则会发现会顺序调用,负载均衡
                      # 如果设置为false 则使用spring-cloud-loadbalancer的BlockingLoadBalancerClient替代
      cache:
        caffeine:
          spec: initialCapacity=50,maximumSize=500,expireAfterWrite=10s

feign:
  hystrix:
    enabled: true # 打开断路器

  httpclient:
    enabled: true # 默认true
    connection-timeout: 2000 # 连接超时默认值