server:
  port: 8861

spring:
  application:
    name: xc-zookeeper-client

  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
    discovery:
      enabled: true # 只开启服务发现

feign:
  hystrix:
    enabled: true # 打开断路器
